### ISSUE TITLE
Test case kiểm tra thông báo lỗi khi nhập lại password trong quá trình đăng kí tài khoản					

### ISSUE THREAD

**Issue by lehoan1810** [puimekster/app_pregnant#31]

**Comment by AQ1011** [comment]
[Kiem tra thong bao loi khi nhap lai password trong qua trinh đang ki tai khoan.xls](https://github.com/puimekster/app_pregnant/files/6448849/Kiem.tra.thong.bao.loi.khi.nhap.lai.password.trong.qua.trinh.dang.ki.tai.khoan.xls)
