### ISSUE TITLE
Test case điền thông tin Phone Number khi đăng nhập thành công vào hệ thống					

### ISSUE THREAD

**Issue by lehoan1810** [puimekster/app_pregnant#32]

**Comment by thedeadsheep** [comment]
[Đien thong tin Phone Number khi đang nhap thanh cong vao he thong.xls](https://github.com/puimekster/app_pregnant/files/6449170/Dien.thong.tin.Phone.Number.khi.dang.nhap.thanh.cong.vao.he.thong.xls)
