### ISSUE TITLE
Test case Thông báo lỗi khi Điền thông tin Phone Number không phù hợp khi đăng nhập thành công vào hệ thống					

### ISSUE THREAD

**Issue by lehoan1810** [puimekster/app_pregnant#33]

**Comment by thedeadsheep** [comment]
[Thong bao loi khi đien thong tin Phone Number khong phu hop khi đang nhap thanh cong vao he thong.xls](https://github.com/puimekster/app_pregnant/files/6449163/Thong.bao.loi.khi.dien.thong.tin.Phone.Number.khong.phu.hop.khi.dang.nhap.thanh.cong.vao.he.thong.xls)
