### ISSUE TITLE
Test case thông báo lỗi nhập password không trùng khớp với new password trong quá trình đăng nhập vào hệ thống					

### ISSUE THREAD

**Issue by lehoan1810** [puimekster/app_pregnant#36]

**Comment by AQ1011** [comment]
[thong bao loi nhap password khong trung khop voi new password trong qua trinh đang nhap vao he thong.xls](https://github.com/puimekster/app_pregnant/files/6448845/thong.bao.loi.nhap.password.khong.trung.khop.voi.new.password.trong.qua.trinh.dang.nhap.vao.he.thong.xls)
