### ISSUE TITLE
Test case thông báo lỗi nhập password không đúng định dạng trong quá trình thay đổi mật khẩu					

### ISSUE THREAD

**Issue by lehoan1810** [puimekster/app_pregnant#37]

**Comment by AQ1011** [comment]
[thong bao loi nhap password khong đung đinh dang trong qua trinh thay đoi mat khau.xls](https://github.com/puimekster/app_pregnant/files/6448842/thong.bao.loi.nhap.password.khong.dung.dinh.dang.trong.qua.trinh.thay.doi.mat.khau.xls)
