### ISSUE TITLE
Đặc tả yêu cầu phần mềm sử dụng bảng (mô tả action trong ngôn ngữ cấu trúc)

### ISSUE THREAD

**Issue by lehoan1810** [puimekster/app_pregnant#8]

**Comment by AQ1011** [comment]
[Đặc tả yêu cầu phần mềm sử dụng bảng.pdf](https://github.com/puimekster/app_pregnant/files/6215313/D.c.t.yeu.c.u.ph.n.m.m.s.d.ng.b.ng.pdf)
